### ISSUE TITLE
grapher.target works, but grapher.nearest doesn't

### ISSUE THREAD

**Issue by danpaulsmith** [ayasdi/grapher-target#1]
http://jsbin.com/poyajijoci/1/edit?js,console,output

**Comment by dannycochran** [comment]
looks like a typo. will push something shortly:
https://github.com/ayasdi/grapher/pull/6/files

**Comment by cixzhang** [comment]
https://github.com/ayasdi/grapher/pull/6

This pull request in Grapher should fix this.
